require('config.options')
require('config.keymaps')
require('config.autocmds')
require('config.statusline')
require('config.lsp')

require('plugins.telescope')
require('plugins.oil')
require('plugins.nvim-treesitter')
require('plugins.gruber-darker')
require('plugins.mini-pairs')
require('plugins.nvim-highlight-colors')
require('plugins.gitsigns')
require('plugins.trouble')
