return {
    { 'neovim/nvim-lspconfig' },
    { 'hrsh7th/nvim-cmp' },
    { 'hrsh7th/cmp-nvim-lsp' },
    { 'hrsh7th/cmp-buffer' },
    { 'hrsh7th/cmp-path' },
    { 'saadparwaiz1/cmp_luasnip' },
    { 'L3MON4D3/LuaSnip' },
    { 'hrsh7th/cmp-vsnip' },
    { 'simrat39/rust-tools.nvim' },
    { 'williamboman/mason.nvim' },
    { 'williamboman/mason-lspconfig.nvim' },
    { 'mfussenegger/nvim-dap' },
    { 'mfussenegger/nvim-lint' },
    { 'mhartington/formatter.nvim' },
}
