return {
    { 'nvim-lua/plenary.nvim' },
    { 'nvim-telescope/telescope.nvim' },
    { 'tiagovla/scope.nvim' },
    { 'akinsho/toggleterm.nvim' },
    { 'MunifTanjim/nui.nvim' },
    { 'folke/which-key.nvim' },
    { 'windwp/nvim-autopairs' },
    { 'nvim-lua/popup.nvim' },
    { 'folke/trouble.nvim' },
    { 'lukas-reineke/indent-blankline.nvim' },
    { 'nvim-neo-tree/neo-tree.nvim' },
    { 'BurntSushi/ripgrep' },
    { 'sharkdp/fd' },
    { 'andweeb/presence.nvim' },
    { 'CRAG666/code_runner.nvim' },
    { 'tpope/vim-fugitive' },
}
